name: gbt
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy>=1.24
  - pandas>=2.0
  - scikit-learn>=1.3
  - matplotlib>=3.7
  - pip:
      - shap>=0.44.0
      - streamlit>=1.36.0
